### ISSUE TITLE
text classification with cnn

### ISSUE THREAD

**Issue by alanyuchenhou** [yuchenhou/rat#2]
## paper

[Character-level Convolutional Networks for Text Classification](http://papers.nips.cc/paper/5782-character-level-convolutional-networks-for-text-classification)
## problem
- input: a character sequence of a restarant review (e.g., fabulousseafoodhotpot)
- output: a bool value indicating if review is positive (e.g., true)
## approach

use cnn with one-hot encoding for each character
## comment

model is not clearly described

**Comment by alanyuchenhou** [comment]
A cnn reads the entire sequence in one go, very unnatural. As a comparison, a rnn reads the sequence one (or a couple of) letters at a time, more like a human (more natural). So my intuition is a rnn will work better for this case.

**Comment by ghost** [comment]
The rnn seems to make the assumption that the sequence is time-ordered. But that's not the case for a DNA sequence. I've attached two papers that take more of a cnn approach for sequence analysis. They are both a bit over-complicated and specialized to their particular task, but they give you an idea of the approach.
[Alipanahi-NatBioTech-2015.pdf](https://github.com/yuchenhou/rat/files/473567/Alipanahi-NatBioTech-2015.pdf)
[Lanchantin-ICLR-2016.pdf](https://github.com/yuchenhou/rat/files/473568/Lanchantin-ICLR-2016.pdf)

**Comment by alanyuchenhou** [comment]
I've seen RNN handle many types of sequences, including text, and DNA sequence and text look the same to me. So I think RNN will work - it's just I don't know when RNN is more accurate than CNN. I also find the two papers have too much biological information to see the real data and model. Do we have any biology students working in this project? I'd like to make sure if this text classification approach is what they want.

**Comment by ghost** [comment]
Don't know of any students here working on applying DL to genomic sequences. You can try RNNs, but I'm not ready to rule out CNNs. As you can see from the Lanchantin paper, they are using a one-hot method over the sequence window (a 4xW "image", where W is the window size). I think that is worth a try.

**Comment by alanyuchenhou** [comment]
OK. I'll try the one-hot encoding with CNN.

**Comment by alanyuchenhou** [comment]
The accuracy with respect to segment length (the number of bases in a DNA sample):

| segment_length | accuracy |
| --- | --- |
| 200 | 0.825 |
| 500 | 0.937 |
| 1000 | 0.875 |

**Comment by ghost** [comment]
Thanks for the quick results. They look promising. What are the specifics of the network topology? Also, what is the accuracy of the majority-class classifier (i.e., just guessing every example is a non-DMR) for each window size?
